### ISSUE TITLE
Upload to Maven Central

### ISSUE THREAD

**Issue by czyzby** [Rickodesea/GdxState#1]
Including a jar directly in your repository is... not exactly the best approach, and definitely not easy to maintain for you _and_ your users. Chances are most people won't bother to include this in their projects without Maven/Gradle support. (Full disclosure: I haven't checked out your library in action yet.)

I'd start with moving the jar to the [releases](https://github.com/Rickodesea/GdxState/releases) section and then uploading it to [Maven Central](http://central.sonatype.org/pages/ossrh-guide.html). Finally, you could try to add this as a third-party extension to the [gdx-setup](https://github.com/libgdx/libgdx/wiki/Third-Party-Extension-Support).

**Comment by Rickodesea** [comment]
Thanks.  I appreciate your comment.  I will continue to work at it.
